version: '3.7'
services:
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: always
    volumes:
      - ./config:/config
    deploy:
      resources:
          limits:
            memory: 256M
    logging:
      options:
        max-size: 128k
