version: '3.7'
services:
  openvpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: always
    volumes:
      - ./openvpn:/etc/openvpn
    deploy:
      resources:
          limits:
            memory: 256M
    logging:
      options:
        max-size: 128k
