version: "3"
services:
  signal:
    image: pionwebrtc/ion:latest-signal
    network_mode: "service:nats"
    restart: always
    depends_on:
      - nats
    volumes:
      - ./signal.toml:/configs/signal.toml
    deploy:
      resources:
          limits:
            memory: 256M
    logging:
      options:
        max-size: 128k
  nats: # 位于别处的nats
    image: marcnuri/port-forward
    ports: # 给signal用的端口
    #因为signal的network_mode是service:nats没法端口转发
      - "5551:5551/tcp"
    restart: always
    environment:
      REMOTE_HOST: ${NATS_ADDR}
      REMOTE_PORT: ${NATS_PORT}
      LOCAL_PORT: '4222'
