version: "3"
services:
  sfu:
    build:
      context: ../ion
      dockerfile: docker/sfu.Dockerfile
    network_mode: "service:nats"
    restart: always
    depends_on:
      - nats
    volumes:
      - ./sfu.toml:/configs/sfu.toml
    deploy:
      resources:
          limits:
            memory: 256M
    logging:
      options:
        max-size: 128k
  nats: # 位于别处的nats
    image: marcnuri/port-forward
    ports: # 给sfu用的端口
    #因为sfu的network_mode是service:nats没法端口转发
      - "5000:5000/udp"
    restart: always
    environment:
      REMOTE_HOST: ${NATS_ADDR}
      REMOTE_PORT: ${NATS_PORT}
      LOCAL_PORT: '4222'
