# from https://github.com/pion/ion/blob/master/configs/app-room.toml
[global]
# data center id
dc = "dc1"

[log]
level = "info"
# level = "debug"

[nats]
url = "nats://127.0.0.1:4222"

[redis]
addrs = [":6379"]
password = ""
db = 0